### ISSUE TITLE
setup.py missing

### ISSUE THREAD

**Issue by JEFworks** [berenslab/t-simcne#1]
Hello,

I'm interesting to trying out `t-simcne`. However, when I try to install it via `pip install -e .` following the instructions under **Implementation**, I encounter the following error:

```
> git clone git@github.com:berenslab/t-simcne.git
> cd t-simcne
> cd cnexp
> pip install -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode
```

It seems like there is a `setup.py` script missing from the `cnexp/` folder. 

Best,
Jean

**Comment by JEFworks** [comment]
In case anyone else encounters this error: I was able to solve this issue by upgrading pip to from v21.1.3 to v22.3.1 and also moving the `pyproject.toml` to the `cnexp/` folder. 

Thanks anyway!

**Comment by dkobak** [comment]
Hi Jean, thanks for the interest. Just want to say that @jnboehm is soon going to extend the README and add more specific instructions and examples of how to run t-SimCNE. At the moment it can be a bit cryptic, but we are working on it!

**Comment by JEFworks** [comment]
Thanks Dmitry! Looking forward to it!
