### ISSUE TITLE
Multiple values for keyword argument 'out_dim'

### ISSUE THREAD

**Issue by erikhagendorn** [berenslab/t-simcne#10]
It appears a recent commit is causing the following exception to be thrown when initializing the `PLtSimCNE` model for the final stage:

`TypeError: tsimcne.tsimcne.PLtSimCNE() got multiple values for keyword argument 'out_dim'`

The `train_args` dictionary already has `out_dim`, which is causing this exception. 

The following line should be removed:
https://github.com/berenslab/t-simcne/blob/e2988f5cb2c86c321e5bad3bc1c968200097def0/tsimcne/tsimcne.py#L478

I am able to replicate this error by running the example code from the readme (I'm setting `total_epochs=[1, 1, 1]` to get to stage 3 quicker).

**Comment by dkobak** [comment]
Thanks a lot!

Nik @jnboehm we should probably add some unit tests, not necessarily automatic, but at least a script that should be run every time before a commit. Something along the lines of running the code for `total_epochs=[1, 1, 1]`, or checking that the returned labels are identical to the original ones (I'm referring to another bug that you mentioned recently), etc.

**Comment by jnboehm** [comment]
Hi again!  Thanks for bringing this up. In fact I had already noticed this error and fixed it in my local version, but forgot to push it. Will fix that now and push a new version
