### ISSUE TITLE
Is the raw data available?

### ISSUE THREAD

**Issue by niniack** [berenslab/t-simcne#14]
Hi, 

Thanks for sharing this repository! Since this is pretty computationally heavy, even for CIFAR-10, I was wondering if y'all would be open to making available the raw results you have for the datasets you demonstrated in the paper (cifar10,100)? 

Thanks!

**Comment by dkobak** [comment]
Hi, thanks for asking! Just to clarify: Do you mean the final 2D coordinates of points that we show in the paper?

**Comment by niniack** [comment]
yepp the 2D coordinates! I'm not sure what the most appropriate format would be...but really anything works for me. I am hoping to do some "distance measurements" between classes of the cifar datasets. Just wanted to ask if you guys had the results handy, it would save a bunch of time!

**Comment by dkobak** [comment]
Yes I think we can simply upload the 2D coordinates as CSV to this repo. Just need to make sure that the order of samples is the same as in some widely available CIFAR data (in PyTorch?) so that you would know which 2D coordinate corresponds to which image.

**Comment by niniack** [comment]
Gotcha, that would be incredible! I'm using Pytorch, so the ordering from there works for me, but again, happy with anything you're able to provide.

Please let me know if there is something I can do to make it easier for you, thanks!

**Comment by jnboehm** [comment]
Hi there!

I've attached a npz/zip file that has the 2D embeddings of cifar10 and cifar100 which we show in the paper.  I also added the labels there, although they shouldn't differ from what the pytorch dataset would return. 

[embeddings.zip](https://github.com/berenslab/t-simcne/files/14652893/embeddings.zip)

You can load the data as follows:
```python

npz = np.load("embeddings.zip")
c100 = npz["c100/data"]
c100_labels = npz["c100/labels"]
# replace c100 with c10 for cifar10
```

Hope that helps with your analysis!  Out of curiosity, what do you want to do with the 2D coordinates?

If you need anything else in relation to those embeddings, feel free to reopen this issue again!

**Comment by dkobak** [comment]
Cool. Do you want to push it somewhere into the actual repo? Could be convenient.

**Comment by niniack** [comment]
Thank y'all for the swift help! If this project goes somewhere, I will be sure to acknowledge your kindness :) I will reach out if I run into any questions about the data! 

@jnboehm I am trying to do some interpretability work in a multi-task setting for a few different model architectures. The CIFAR datasets are more wieldy so I'm working with those at the moment. The idea is to curate what order the model learns these classes in order to do the study. It's not really about improving the model, more about understanding what changes when the order of tasks changes. In order to do this curation, I wanted to somehow quantify how "different" or "similar" classes are to each other, especially in something a bit larger like CIFAR100. I figured I could take a look at embeddings to justify choices.

**Comment by jnboehm** [comment]
Nice, thanks for the elaboration and good luck!  

@dkobak done.
