### ISSUE TITLE
Bug when running example [uninitialized dataset_transforms]

### ISSUE THREAD

**Issue by fabioseel** [berenslab/t-simcne#15]
When running the usage example, an Type Error is raised when mapping the images to the 2D coordinates:
`Y = tsimcne.transform(dataset_full)`

_TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  [...]
  File "[...]/t-simcne/tsimcne/imagedistortions.py", line 159, in __getitem__
    item1 = self.transform(orig_item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable_

It seems that this is due to line 623 in tsimcne.py in make_dataloader:
`            data_transform = self.data_transform`
_self.data_transform_ is still _None_ here.

Additionally this line prohibits passing a data_transform to tsimcne.transform is not possible at the moment, as it gets overwritten.

**Comment by jnboehm** [comment]
Thank you for the report Fabio :)

Ah, yeah that happens when `transform` is called before the model has been `fit`ted, because some initialization is happening there that `transform` depends on.
