### ISSUE TITLE
Issues when running the usage example

### ISSUE THREAD

**Issue by YingfanWang** [berenslab/t-simcne#3]
Hi!

I'm interested in t-simcne and tried the usage example in README. However, I encountered an issue when running tsimcne.fit() as follow:
 
<img width="1027" alt="Screen Shot 2023-10-19 at 10 32 20 PM" src="https://github.com/berenslab/t-simcne/assets/56569519/e95e1a1b-5c37-4429-ab04-6b353af59a78">

Do you have any clue how to fix it? I'm using the following package versions:

lightning=2.1.0
python=3.8
torch=2.0.0

Which versions are you using for t-simcne?

Thank you so much in advance!

**Comment by jnboehm** [comment]
Thanks for bringing this up!

I found this related issue https://github.com/Zasder3/train-CLIP/issues/36, so it seems to not work with your version and I can reproduce your error.  In the meantime I guess you'll have to downgrade the lightning version but I'll try to get around to fixing this issue soon.

**Comment by jnboehm** [comment]
I noticed that I messed up the indentation when refactoring the code and that was the cause for the error.  So my previous comment was incorrect, but it should be fixed now.  

Let me know if this issue persists for you, but I can now run this with torch 2.0.1 and lightning 2.0.8 (on python 3.11).
